services:
  psql_database:
    container_name: psql_database
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dcf_db
      POSTGRES_SSLMODE: disable
    ports:
      - "5433:5432"
    volumes:
      - psqldb:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}
    networks:
      - app-network
    environment:
      - REDIS_PASSWORD=password
volumes:
  psqldb:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
